package woowacourse.shopping.view.cart

enum class CartEvent {
    LOAD_SHOPPING_CART_FAILURE,
    REMOVE_SHOPPING_CART_PRODUCT_FAILURE,
    UPDATE_SHOPPING_CART_PRODUCT_SUCCESS,
    UPDATE_SHOPPING_CART_PRODUCT_FAILURE,
    PLUS_CART_ITEM_QUANTITY_FAILURE,
    MINUS_CART_ITEM_QUANTITY_FAILURE,
}
