package woowacourse.shopping.ui.cart.listener

import woowacourse.shopping.ui.OnItemQuantityChangeListener

interface ShoppingCartItemListener : OnItemQuantityChangeListener, OnCartItemSelectedListener
