package woowacourse.shopping.backend

import woowacourse.shopping.model.Price
import woowacourse.shopping.model.Product
import woowacourse.shopping.model.ProductTitle

object MockProductSeedData {
    val products: List<Product> =
        listOf(
            Product(id = 1L, title = ProductTitle("에센스 래시 프린세스 마스카라"), price = Price(9990), imageUrl = "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp"),
            Product(id = 2L, title = ProductTitle("거울 아이섀도우 팔레트"), price = Price(19990), imageUrl = "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp"),
            Product(id = 3L, title = ProductTitle("파우더 케이스"), price = Price(14990), imageUrl = "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp"),
            Product(id = 4L, title = ProductTitle("레드 립스틱"), price = Price(12990), imageUrl = "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp"),
            Product(id = 5L, title = ProductTitle("레드 네일 폴리시"), price = Price(8990), imageUrl = "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp"),
            Product(id = 6L, title = ProductTitle("캘빈클라인 CK 원 향수"), price = Price(49990), imageUrl = "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp"),
            Product(id = 7L, title = ProductTitle("샤넬 코코 누아르 오 드 퍼퓸"), price = Price(129990), imageUrl = "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp"),
            Product(id = 8L, title = ProductTitle("디올 쟈도르 향수"), price = Price(89990), imageUrl = "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"),
            Product(id = 9L, title = ProductTitle("돌체 샤인 오 드 퍼퓸"), price = Price(69990), imageUrl = "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp"),
            Product(id = 10L, title = ProductTitle("구찌 블룸 오 드 퍼퓸"), price = Price(79990), imageUrl = "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp"),
            Product(id = 11L, title = ProductTitle("아니발레 콜롬보 침대"), price = Price(1899990), imageUrl = "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp"),
            Product(id = 12L, title = ProductTitle("아니발레 콜롬보 소파"), price = Price(2499990), imageUrl = "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp"),
            Product(id = 13L, title = ProductTitle("아프리칸 체리 협탁"), price = Price(299990), imageUrl = "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp"),
            Product(id = 14L, title = ProductTitle("놀 사리넨 컨퍼런스 의자"), price = Price(499990), imageUrl = "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp"),
            Product(id = 15L, title = ProductTitle("원목 욕실 세면대 거울 세트"), price = Price(799990), imageUrl = "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp"),
            Product(id = 16L, title = ProductTitle("사과"), price = Price(1990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp"),
            Product(id = 17L, title = ProductTitle("소고기 스테이크"), price = Price(12990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp"),
            Product(id = 18L, title = ProductTitle("고양이 사료"), price = Price(8990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp"),
            Product(id = 19L, title = ProductTitle("닭고기"), price = Price(9990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp"),
            Product(id = 20L, title = ProductTitle("식용유"), price = Price(4990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp"),
            Product(id = 21L, title = ProductTitle("오이"), price = Price(1490), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp"),
            Product(id = 22L, title = ProductTitle("강아지 사료"), price = Price(10990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp"),
            Product(id = 23L, title = ProductTitle("계란"), price = Price(2990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp"),
            Product(id = 24L, title = ProductTitle("생선 스테이크"), price = Price(14990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp"),
            Product(id = 25L, title = ProductTitle("초록 파프리카"), price = Price(1290), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp"),
            Product(id = 26L, title = ProductTitle("청양고추"), price = Price(990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp"),
            Product(id = 27L, title = ProductTitle("꿀 단지"), price = Price(6990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp"),
            Product(id = 28L, title = ProductTitle("아이스크림"), price = Price(5490), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp"),
            Product(id = 29L, title = ProductTitle("주스"), price = Price(3990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp"),
            Product(id = 30L, title = ProductTitle("키위"), price = Price(2490), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp"),
            Product(id = 31L, title = ProductTitle("레몬"), price = Price(790), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/lemon/thumbnail.webp"),
            Product(id = 32L, title = ProductTitle("우유"), price = Price(3490), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/milk/thumbnail.webp"),
            Product(id = 33L, title = ProductTitle("오디"), price = Price(4990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/mulberry/thumbnail.webp"),
            Product(id = 34L, title = ProductTitle("네스카페 커피"), price = Price(7990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/nescafe-coffee/thumbnail.webp"),
            Product(id = 35L, title = ProductTitle("감자"), price = Price(2290), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp"),
            Product(id = 36L, title = ProductTitle("프로틴 파우더"), price = Price(19990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/protein-powder/thumbnail.webp"),
            Product(id = 37L, title = ProductTitle("적양파"), price = Price(1990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/red-onions/thumbnail.webp"),
            Product(id = 38L, title = ProductTitle("쌀"), price = Price(5990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/rice/thumbnail.webp"),
            Product(id = 39L, title = ProductTitle("탄산음료"), price = Price(1990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp"),
            Product(id = 40L, title = ProductTitle("딸기"), price = Price(3990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/strawberry/thumbnail.webp"),
            Product(id = 41L, title = ProductTitle("티슈 박스"), price = Price(2490), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp"),
            Product(id = 42L, title = ProductTitle("생수"), price = Price(990), imageUrl = "https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp"),
            Product(id = 43L, title = ProductTitle("장식용 그네"), price = Price(59990), imageUrl = "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/thumbnail.webp"),
            Product(id = 44L, title = ProductTitle("패밀리 트리 포토 프레임"), price = Price(29990), imageUrl = "https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp"),
            Product(id = 45L, title = ProductTitle("인테리어 식물 오브제"), price = Price(39990), imageUrl = "https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/thumbnail.webp"),
            Product(id = 46L, title = ProductTitle("화분"), price = Price(14990), imageUrl = "https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/thumbnail.webp"),
            Product(id = 47L, title = ProductTitle("테이블 램프"), price = Price(49990), imageUrl = "https://cdn.dummyjson.com/product-images/home-decoration/table-lamp/thumbnail.webp"),
            Product(id = 48L, title = ProductTitle("대나무 뒤집개"), price = Price(7990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/bamboo-spatula/thumbnail.webp"),
            Product(id = 49L, title = ProductTitle("블랙 알루미늄 컵"), price = Price(5990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/black-aluminium-cup/thumbnail.webp"),
            Product(id = 50L, title = ProductTitle("블랙 거품기"), price = Price(9990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/black-whisk/thumbnail.webp"),
            Product(id = 51L, title = ProductTitle("박스형 블렌더"), price = Price(39990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/thumbnail.webp"),
            Product(id = 52L, title = ProductTitle("카본 스틸 웍"), price = Price(29990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/carbon-steel-wok/thumbnail.webp"),
            Product(id = 53L, title = ProductTitle("도마"), price = Price(12990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/chopping-board/thumbnail.webp"),
            Product(id = 54L, title = ProductTitle("옐로 시트러스 스퀴저"), price = Price(8990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/citrus-squeezer-yellow/thumbnail.webp"),
            Product(id = 55L, title = ProductTitle("에그 슬라이서"), price = Price(6990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/egg-slicer/thumbnail.webp"),
            Product(id = 56L, title = ProductTitle("전기 스토브"), price = Price(49990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp"),
            Product(id = 57L, title = ProductTitle("미세망 채반"), price = Price(9990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/fine-mesh-strainer/thumbnail.webp"),
            Product(id = 58L, title = ProductTitle("포크"), price = Price(3990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/fork/thumbnail.webp"),
            Product(id = 59L, title = ProductTitle("유리컵"), price = Price(4990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/glass/thumbnail.webp"),
            Product(id = 60L, title = ProductTitle("블랙 강판"), price = Price(10990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/grater-black/thumbnail.webp"),
            Product(id = 61L, title = ProductTitle("핸드 블렌더"), price = Price(34990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/hand-blender/thumbnail.webp"),
            Product(id = 62L, title = ProductTitle("아이스 큐브 트레이"), price = Price(5990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/ice-cube-tray/thumbnail.webp"),
            Product(id = 63L, title = ProductTitle("키친 체"), price = Price(7990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/kitchen-sieve/thumbnail.webp"),
            Product(id = 64L, title = ProductTitle("주방용 칼"), price = Price(14990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/knife/thumbnail.webp"),
            Product(id = 65L, title = ProductTitle("런치박스"), price = Price(12990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/lunch-box/thumbnail.webp"),
            Product(id = 66L, title = ProductTitle("전자레인지"), price = Price(89990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/microwave-oven/thumbnail.webp"),
            Product(id = 67L, title = ProductTitle("머그 트리 거치대"), price = Price(15990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/mug-tree-stand/thumbnail.webp"),
            Product(id = 68L, title = ProductTitle("프라이팬"), price = Price(24990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/pan/thumbnail.webp"),
            Product(id = 69L, title = ProductTitle("접시"), price = Price(3990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/plate/thumbnail.webp"),
            Product(id = 70L, title = ProductTitle("레드 집게"), price = Price(6990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/red-tongs/thumbnail.webp"),
            Product(id = 71L, title = ProductTitle("유리뚜껑 실버 냄비"), price = Price(39990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/silver-pot-with-glass-cap/thumbnail.webp"),
            Product(id = 72L, title = ProductTitle("슬롯 터너"), price = Price(8990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/slotted-turner/thumbnail.webp"),
            Product(id = 73L, title = ProductTitle("향신료 선반"), price = Price(19990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/spice-rack/thumbnail.webp"),
            Product(id = 74L, title = ProductTitle("스푼"), price = Price(4990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/spoon/thumbnail.webp"),
            Product(id = 75L, title = ProductTitle("트레이"), price = Price(16990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/tray/thumbnail.webp"),
            Product(id = 76L, title = ProductTitle("원목 밀대"), price = Price(11990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/wooden-rolling-pin/thumbnail.webp"),
            Product(id = 77L, title = ProductTitle("옐로 필러"), price = Price(5990), imageUrl = "https://cdn.dummyjson.com/product-images/kitchen-accessories/yellow-peeler/thumbnail.webp"),
            Product(id = 78L, title = ProductTitle("애플 맥북 프로 14인치 스페이스 그레이"), price = Price(1999990), imageUrl = "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp"),
            Product(id = 79L, title = ProductTitle("ASUS 젠북 프로 듀얼 스크린 노트북"), price = Price(1799990), imageUrl = "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp"),
            Product(id = 80L, title = ProductTitle("화웨이 메이트북 X 프로"), price = Price(1399990), imageUrl = "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp"),
            Product(id = 81L, title = ProductTitle("레노버 요가 920"), price = Price(1099990), imageUrl = "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp"),
            Product(id = 82L, title = ProductTitle("델 XPS 13 9300 노트북"), price = Price(1499990), imageUrl = "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp"),
            Product(id = 83L, title = ProductTitle("블루 블랙 체크 셔츠"), price = Price(29990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp"),
            Product(id = 84L, title = ProductTitle("기가바이트 어로스 남성 티셔츠"), price = Price(24990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/thumbnail.webp"),
            Product(id = 85L, title = ProductTitle("남성 체크 셔츠"), price = Price(34990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp"),
            Product(id = 86L, title = ProductTitle("남성 반소매 셔츠"), price = Price(19990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp"),
            Product(id = 87L, title = ProductTitle("남성 체크 셔츠 클래식"), price = Price(27990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/thumbnail.webp"),
            Product(id = 88L, title = ProductTitle("나이키 에어 조던 1 레드 블랙"), price = Price(149990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp"),
            Product(id = 89L, title = ProductTitle("나이키 야구 클리츠"), price = Price(79990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/thumbnail.webp"),
            Product(id = 90L, title = ProductTitle("푸마 퓨처 라이더 트레이너"), price = Price(89990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp"),
            Product(id = 91L, title = ProductTitle("스포츠 스니커즈 오프화이트 레드"), price = Price(119990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp"),
            Product(id = 92L, title = ProductTitle("스포츠 스니커즈 오프화이트 레드 2"), price = Price(109990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp"),
            Product(id = 93L, title = ProductTitle("브라운 가죽 벨트 시계"), price = Price(89990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/thumbnail.webp"),
            Product(id = 94L, title = ProductTitle("론진 마스터 컬렉션"), price = Price(1499990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/thumbnail.webp"),
            Product(id = 95L, title = ProductTitle("롤렉스 첼리니 데이트 블랙 다이얼"), price = Price(8999990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/thumbnail.webp"),
            Product(id = 96L, title = ProductTitle("롤렉스 첼리니 문페이즈"), price = Price(12999990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/thumbnail.webp"),
            Product(id = 97L, title = ProductTitle("롤렉스 데이저스트"), price = Price(10999990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/thumbnail.webp"),
            Product(id = 98L, title = ProductTitle("롤렉스 서브마리너 시계"), price = Price(13999990), imageUrl = "https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp"),
            Product(id = 99L, title = ProductTitle("아마존 에코 플러스"), price = Price(99990), imageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp"),
            Product(id = 100L, title = ProductTitle("애플 에어팟"), price = Price(129990), imageUrl = "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp"),
        )
}
