package woowacourse.shopping.view.recommend

enum class RecommendEvent {
    LOAD_RECOMMEND_PRODUCTS_FAILURE,
    LOAD_SHOPPING_CART_FAILURE,
    LOAD_ALL_PRODUCTS_FAILURE,
    ADD_CART_ITEM_FAILURE,
    PLUS_CART_ITEM_FAILURE,
    REMOVE_CART_ITEM_FAILURE,
    MINUS_CART_ITEM_FAILURE,
}
