package woowacourse.shopping.view.product

enum class ProductsEvent {
    LOAD_MORE_PRODUCT_FAILURE,
    UPDATE_SHOPPING_CART_FAILURE,
    LOAD_SHOPPING_CART_QUANTITY_FAILURE,
    LOAD_RECENT_PRODUCTS_FAILURE,
    LOAD_SHOPPING_CART_FAILURE,
}
