package woowacourse.shopping.constant

object ShoppingColor {
    const val APP_BAR_COLOR = 0xFF555555
    const val CART_ADD_BUTTON_COLOR = 0xFF14C3B1
    const val PRODUCT_DETAIL_BACKGROUND_COLOR = 0xFFE0E0E0
    const val CART_PAGE_BUTTON_ACTIVE_COLOR = 0xFF04C09E
    const val CART_PAGE_BUTTON_INACTIVE_COLOR = 0xFFAAAAAA
    const val PAYMENT_BUTTON_COLOR = 0xFF13C7B3
    const val PAYMENT_DIVIDER_COLOR = 0xFFEAEAEA
    const val PAYMENT_CARD_BORDER_COLOR = 0xFFBEBEBE
    const val PAYMENT_SUMMARY_BACKGROUND_COLOR = 0xFFF8F8F8
    const val PAYMENT_DESCRIPTION_GRAY = 0xFF7D7D7D
    const val PAYMENT_TITLE_GRAY = 0xFF555555
}
