package woowacourse.shopping.view.shoppingCart

enum class ShoppingCartEvent {
    UPDATE_SHOPPING_CART_FAILURE,
    REMOVE_SHOPPING_CART_PRODUCT_FAILURE,
    DECREASE_SHOPPING_CART_PRODUCT_FAILURE,
    ADD_SHOPPING_CART_PRODUCT_FAILURE,
}
