package woowacourse.shopping.presentation.view.catalog.event

enum class CatalogMessageEvent {
    FETCH_PRODUCTS_FAILURE,
    FETCH_CART_ITEM_COUNT_FAILURE,
    INCREASE_PRODUCT_TO_CART_FAILURE,
    DECREASE_PRODUCT_FROM_CART_FAILURE,
    FIND_PRODUCT_QUANTITY_FAILURE,
    FETCH_RECENT_PRODUCT_FAILURE,
}
